version: "3.9"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: taskmanager
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 20
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    environment:
      DB_URL: jdbc:mysql://db:3306/taskmanager
      DB_USERNAME: app
      DB_PASSWORD: app
      JWT_SECRET: ZXhhbXBsZS1zZWNyZXQtYmFzZTY0LXN0cmluZw==
      JWT_EXPIRATION_MS: 86400000
      PORT: 8080
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    environment:
      VITE_API_BASE: http://localhost:8080
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  db_data:


